### ISSUE TITLE
License

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-sl#1]
Although in the readme you say it is released under academic license, the actual repo contains NCSA license: 
https://github.com/IllinoisCogComp/illinois-sl/blob/master/LICENSE
I think you should replace with this: 
https://github.com/IllinoisCogComp/lbjava/blob/master/LICENSE

**Comment by danyaljj** [comment]
Also a suggestion:  lbjava project uses the license maven plugin to add a small snippet on top of each file:
https://github.com/IllinoisCogComp/lbjava/blob/master/pom.xml#L90-L119

**Comment by danyaljj** [comment]
FYI @shyamupa

**Comment by shyamupa** [comment]
I need to discuss this with Dan and Kai-Wei. Thanks for bringing to notice!

**Comment by KaiWeiChang** [comment]
Hi Shyam, 
As long as it can be recognised as open source license (http://www.opensource.org/licenses/), I'm fine with it. Could you talk to Dan or Mark and see what we should use?

Thanks for the pointer of maven plugin.

**Comment by shyamupa** [comment]
Mark says its open source. I am closing this.
