### ISSUE TITLE
LatentSL works? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-sl#18]
@shyamupa @KaiWeiChang 
I see [AbstractLatentInferenceSolver](https://github.com/danyaljj/illinois-sl/blob/master/src/main/java/edu/illinois/cs/cogcomp/sl/latentsvm/AbstractLatentInferenceSolver.java) for latent struct. learning. Just checking: is it completely functional? Asking because I don't see much documentation/examples on this.

**Comment by KaiWeiChang** [comment]
It is working. But we don't have an interesting application to put in demo. 
You're welcomed to contribute one :-)
