### ISSUE TITLE
Moving utils to core-utils? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-sl#19]
@KaiWeiChang @shyamupa @mssammon 
We are considering moving the[ `utils` folder of lbjava](https://github.com/IllinoisCogComp/lbjava/tree/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/util) to [core-utilities](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/core-utilities). 
@christos-c pointed out that [SL also has similar datastructures](https://github.com/IllinoisCogComp/illinois-sl/tree/master/src/main/java/edu/illinois/cs/cogcomp/sl/util). I have two questions for you: 
1. What do you think about moving ibjava utils folder into core-utils? (and core-utils being dependency of lbjava). 
2. What do you think about moving SL utils folder (as well as lbjava's) into core-utils (and merging potential duplicates)? (and core-utils being dependency of lbjava and SL).

**Comment by shyamupa** [comment]
I am fine with either, as long as SL does not have to rely on something outside of itself or core-utils. Do not want a heavy pom.

**Comment by danyaljj** [comment]
Thanks for the feedback. I will go ahead and send a PR.
