### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by narendergupta** [IllinoisCogComp/illinois-sl#3]
It took me some time to realize that instead of downloading a zip from github, I should go to the cogcomp website and download the jar from there. The problem with downloading zip from github is that it doesn't have the same structure as explained in the README file.

Can we include a link to the download location (http://cogcomp.cs.illinois.edu/page/software_view/illinois-sl) in the README file itself?

**Comment by KaiWeiChang** [comment]
Done.  Thank you!
